import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { Providers } from "@/lib/ReactQueryProvider";
import { Headers } from "@/components/headers/Headers";
import { getSession } from "@/components/utils/CacheSession";
import { SignInButton } from "@/features/auth/SignInButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();
  const user = session?.user?.id;

  if (!user) {
    return (
      <html>
        <body>
          <SignInButton variant="default" bgColor="bg-blue-500" />
        </body>
      </html>
    );
  }

  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#F0F2F5] text-black`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <SessionProvider>
            <Headers />
            {children}
          </SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
